/**
 * Scans posts/*.md (project root, next to src/) and generates
 * src/posts.generated.js — the post registry used by the app. Each file
 * must start with a frontmatter block:
 *
 *   ---
 *   title: My Post
 *   date: 2026-08-09
 *   hidden: true        # optional — hidden posts are excluded from the
 *                       # /posts list (e.g. /about)
 *   ---
 *
 * Posts are ordered by date (newest first). The featured post is the
 * newest visible one. Re-run with `npm run generate` after adding a file.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join, basename, extname } from 'node:path'
import { fileURLToPath } from 'node:url'

const postsDir = fileURLToPath(new URL('../posts/', import.meta.url))
const outFile = fileURLToPath(new URL('../src/posts.generated.js', import.meta.url))

function parseFrontmatter(md) {
  const m = md.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?/)
  const meta = {}
  if (m) {
    for (const line of m[1].split(/\r?\n/)) {
      const i = line.indexOf(':')
      if (i === -1) continue
      const key = line.slice(0, i).trim()
      const value = line.slice(i + 1).trim()
      if (key) meta[key] = value
    }
  }
  return { meta, bodyStart: m ? m[0].length : 0 }
}

const files = readdirSync(postsDir)
  .filter((f) => f.endsWith('.md'))
  .sort()

const posts = files
  .map((file) => {
    const md = readFileSync(join(postsDir, file), 'utf8')
    const { meta } = parseFrontmatter(md)
    return {
      slug: basename(file, extname(file)),
      title: meta.title || basename(file, extname(file)),
      date: meta.date || '',
      hidden: meta.hidden === 'true',
      file,
    }
  })
  // newest date first; same date → filename descending (stable, and keeps
  // the welcome post first when everything shares a date)
  .sort((a, b) =>
    a.date < b.date ? 1 : a.date > b.date ? -1 : a.file < b.file ? 1 : -1
  )

let out = `// AUTO-GENERATED by scripts/generate-posts.js — do not edit.\n` +
  `// Run \`npm run generate\` after adding or changing a file in posts/.\n\n` +
  `// strips the frontmatter block so it is never rendered as body text\n` +
  `const strip = (md) => md.replace(/^---\\r?\\n[\\s\\S]*?\\r?\\n---\\r?\\n?/, '')\n\n`
for (const post of posts) {
  const ident = post.slug.replace(/[^A-Za-z0-9_]/g, '_') || 'post'
  out += `import ${ident} from '../posts/${post.file}?raw'\n`
}
out += `\nexport const posts = [\n`
for (const post of posts) {
  out += `  { slug: ${JSON.stringify(post.slug)}, title: ${JSON.stringify(post.title)}, date: ${JSON.stringify(post.date)}, hidden: ${post.hidden}, content: strip(${post.slug.replace(/[^A-Za-z0-9_]/g, '_') || 'post'}) },\n`
}
out += `]\n\n`
out += `export const getPost = (slug) => posts.find((p) => p.slug === slug)\n\n`
out += `export const featuredPost = posts.find((p) => !p.hidden)\n`

writeFileSync(outFile, out)
console.log(`generate-posts: ${posts.length} post(s) → ${outFile}`)
